// <auto-generated />
using System;
using FundamentalData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FundamentalData.Migrations
{
    [DbContext(typeof(FundamentalDataContext))]
    [Migration("20220612165535_InitialCommit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataStructures.FundamentalData.BalanceSheet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("AccountsNotesReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccountsPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccountsReceivableNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccruedLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccruedTaxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccumulatedDepreciation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdditionalPaidinCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AssetsHeldforSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashCashEquivalents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashCashEquivalentsShortTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommonStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentPortionofLongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredCompensation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredRevenueLongTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredRevenueShortTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredTaxAssetsLongTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredTaxAssetsShortTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredTaxLiabilitiesLongTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredTaxLiabilitiesShortTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DerivativeHedgingAssetsLongTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DerivativeHedgingAssetsShortTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscontinuedOperationsLongTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscontinuedOperationsShortTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EquityBeforeMinorityInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinishedGoods")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Goodwill")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTaxesReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IntangibleAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestDividendsPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Inventories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentsinAffiliates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilitiesfromDerivativesHedgingLongTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilitiesfromDerivativesHedgingShortTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilitiesfromDiscontinuedOperationsLongTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilitiesfromDiscontinuedOperationsShortTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermBorrowings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermCapitalLeases")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermInvestmentsReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermMarketableSecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongTermReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinorityInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MiscLongTermAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MiscLongTermLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MiscShortTermAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MiscShortTermLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotesReceivableNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherIntangibleAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherInventory")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherLongTermAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherLongTermLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherPayablesAccruals")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherPostRetirementBenefits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherShareCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherShortTermAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherShortTermLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PayablesAccruals")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PensionLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pensions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PreferredEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrepaidExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrepaidExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrepaidPensionCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PropertyPlantEquipment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PropertyPlantEquipmentNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RawMaterials")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RestatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RetainedEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShareCapitalAdditionalPaidInCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortTermBorrowings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortTermCapitalLeases")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortTermInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLiabilitiesEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNoncurrentAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNoncurrentLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TreasuryStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnbilledRevenues")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WorkInProcess")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("BalanceSheet");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.CashFlowStatement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("AcquisitionofFixedAssetsIntangibles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AcquisitionofIntangibleAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashforAcquisitionofSubsidiaries")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashforJointVentures")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashfromLongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashfromRepaymentofDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashfromRepaymentofLongTermDebtNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashfromRepaymentofShortTermDebtNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashfromRepurchaseofEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeinAccountsPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeinAccountsReceivable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeinCashfromDiscOperationsandOther")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeinFixedAssetsIntangibles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeinInventories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeinOther")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeinWorkingCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DecreaseinCapitalStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DecreaseinLongTermInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredIncomeTaxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepreciationAmortization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DispositionofFixedAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DispositionofFixedAssetsIntangibles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DispositionofIntangibleAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DividendsPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EffectofForeignExchangeRates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FreeCashFlow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncreaseinCapitalStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncreaseinLongTermInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashBeforeDiscOperationsandFX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashBeforeFX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashfromAcquisitionsDivestitures")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashfromDiscontinuedOperationsFinancing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashfromDiscontinuedOperationsInvesting")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashfromDiscontinuedOperationsOperating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashfromDivestitures")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashfromFinancingActivities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashfromInvestingActivities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashfromOperatingActivities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetCashfromOtherAcquisitions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetChangeinCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetChangeinLongTermInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetIncomeStartingLine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetIncomefromDiscontinuedOperations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonCashItems")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherAdjustments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherChangeinFixedAssetsIntangibles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherFinancingActivities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherInvestingActivities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherNonCashAdjustments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchaseofFixedAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RepaymentsofLongTermDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RestatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StockBasedCompensation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CashFlowStatement");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("BusinessSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndustryID")
                        .HasColumnType("int");

                    b.Property<int>("MonthFyEnd")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberEmployees")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IndustryID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Filing", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("BalanceSheetID")
                        .HasColumnType("int");

                    b.Property<int?>("CashflowStatementID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncomeStatementID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RestatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BalanceSheetID");

                    b.HasIndex("CashflowStatementID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("IncomeStatementID");

                    b.ToTable("Filings");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.IncomeStatement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("AbnormalDerivatives")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AbnormalGainsLosses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccountingChargesOther")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AcquiredInProcessRD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AssetWriteDown")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsolidatedIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostofFinancingRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostofGoodsServices")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostofOtherRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostofRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentIncomeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredIncomeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepreciationAmortization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscontinuedOperations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DisposalofAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DividendPerShare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EBIT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EBITDA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EBITDAMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EBITMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EPSDiluted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EarlyExtinguishmentofDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EarningsBeforeTaxMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinancingRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ForeignExchangeGainLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FreeCashFlowMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GeneralAdministrative")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrossMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImpairmentofGoodwillIntangibles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeLossInclMinorityInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeLossfromAffiliates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeLossfromAffiliatesNetofTaxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeLossfromContinuingOperations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTaxExpenseBenefitNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceSettlement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestExpenseNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LegalSettlement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MergerAcquisitionExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinorityInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetExtraordinaryGainsLosses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetIncomeCommon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetIncomeNonControllingInt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetProfitMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonOperatingIncomeLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OperatingExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OperatingIncomeLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherAbnormalItems")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherAdjustments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherInvestmentIncomeLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherNonOperatingIncomeLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherOperatingExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherOperatingIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PreferredDividends")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PretaxIncomeLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PretaxIncomeLossAdj")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProvisionforDoubtfulAccounts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ResearchDevelopment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RestatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RestructuringCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaleofBusiness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaleofInvestmentsUnrealizedInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalesServicesRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellingGeneralAdministrative")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellingMarketing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAllowanceCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WeightedAverageShsOut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WeightedAverageShsOutDiluted")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("IncomeStatement");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Industry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SectorID");

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Market", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Sector", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("MarketID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MarketID");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.StockPrice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal?>("AdjClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Dividend")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Company", b =>
                {
                    b.HasOne("DataStructures.FundamentalData.Industry", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Filing", b =>
                {
                    b.HasOne("DataStructures.FundamentalData.BalanceSheet", "BalanceSheet")
                        .WithMany()
                        .HasForeignKey("BalanceSheetID");

                    b.HasOne("DataStructures.FundamentalData.CashFlowStatement", "CashflowStatement")
                        .WithMany()
                        .HasForeignKey("CashflowStatementID");

                    b.HasOne("DataStructures.FundamentalData.Company", "Company")
                        .WithMany("Filings")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataStructures.FundamentalData.IncomeStatement", "IncomeStatement")
                        .WithMany()
                        .HasForeignKey("IncomeStatementID");

                    b.Navigation("BalanceSheet");

                    b.Navigation("CashflowStatement");

                    b.Navigation("Company");

                    b.Navigation("IncomeStatement");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Industry", b =>
                {
                    b.HasOne("DataStructures.FundamentalData.Sector", "Sector")
                        .WithMany("Industries")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Sector", b =>
                {
                    b.HasOne("DataStructures.FundamentalData.Market", "Market")
                        .WithMany("Sectors")
                        .HasForeignKey("MarketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.StockPrice", b =>
                {
                    b.HasOne("DataStructures.FundamentalData.Company", "Company")
                        .WithMany("Prices")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Company", b =>
                {
                    b.Navigation("Filings");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Industry", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Market", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("DataStructures.FundamentalData.Sector", b =>
                {
                    b.Navigation("Industries");
                });
#pragma warning restore 612, 618
        }
    }
}
